# Generated by Django 2.2.10 on 2021-03-11 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_specificationissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_sap_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid sap id', message='Numer SAP produktu składać się z dokładnie 7 cyfr', regex='^([0-9]{7})$')]),
        ),
    ]
