# Generated by Django 2.2.10 on 2021-03-11 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210311_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='index',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(code='invalid index', message='Indeks produktu powinien być w określonym formacie, np. T1034321/26', regex='^$|^(T|R)([0-9]{9})/([0-9]{2})$')]),
        ),
    ]
