# Generated by Django 2.2.10 on 2021-03-11 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210311_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='flat_crush_resistance_tolerance_top',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='wall_thickness_tolerance_bottom',
        ),
        migrations.RemoveField(
            model_name='specification',
            name='wall_thickness_tolerance_top',
        ),
    ]
