# Generated by Django 2.2.10 on 2021-03-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20201022_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='external_diameter_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='internal_diameter_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='length',
        ),
    ]
