language: python
python:
  - "3.6"

services:
  - mysql

install:
  - pip install -r pkg_install_requirements.txt

# Run scripts specified in Jobs rather than one global script.
before_script: 
- mysql -e 'create database test;' -u root

script: skip

jobs:
  include:
    - stage: lint
      script: python -m flake8 --statistics --ignore=E265,E501,F401,F841,*migrations --max-line-length 120 .

    - stage: test
      script: python manage.py test apps --failfast

cache:
  - pip
  - directories:
    # Cache the virtualenv packages folder so virtualenv doesn't waste
    # time installing locally cached packages
    - '/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages'

