# Generated by Django 2.2.10 on 2021-03-11 10:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20201022_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_sap_id',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid sap id', message='Numer SAP klienta powinien składać się z dokładnie 5 cyfr', regex='^([0-9]{5})$')]),
        ),
    ]
